In [1]:
import pandas

In [2]:
sydney = pandas.Series(index=['Mon','Tue','Wed'], data=[37,38,29])

In [3]:
melbourne = pandas.Series(index=['Sun','Mon','Tue'], data=[25,42,41])

In [4]:
sydney - melbourne

Mon   -5.0
Sun    NaN
Tue   -3.0
Wed    NaN
dtype: float64

In [5]:
sydney+1

Mon    38
Tue    39
Wed    30
dtype: int64

In [6]:
import pandas

In [8]:
city_data = pandas.DataFrame({
    'sydney' : sydney,
    'melbourne' : melbourne
})

In [9]:
city_data

     melbourne  sydney
Mon       42.0    37.0
Sun       25.0     NaN
Tue       41.0    38.0
Wed        NaN    29.0

In [10]:
!pip install html5lib
!pip install BeautifulSoup4

Collecting html5lib
  Downloading html5lib-0.999999999-py2.py3-none-any.whl (112kB)
Requirement already satisfied: six in c:\programdata\anaconda2\lib\site-packages (from html5lib)
Requirement already satisfied: setuptools>=18.5 in c:\programdata\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg (from html5lib)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.5.tar.gz
Building wheels for collected packages: webencodings
  Running setup.py bdist_wheel for webencodings: started
  Running setup.py bdist_wheel for webencodings: finished with status 'done'
  Stored in directory: C:\Users\abhisheagrawal\AppData\Local\pip\Cache\wheels\0a\73\c2\1dcc99951b6aeac495e7695505d1837616ca194938f07d1d7b
Successfully built webencodings
Installing collected packages: webencodings, html5lib
Successfully installed html5lib-0.999999999 webencodings-0.5

  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /simple/html5lib/

Requirement already satisfied: BeautifulSoup4 in c:\programdata\anaconda2\lib\site-packages

In [11]:
list_of_tables = pandas.read_html('http://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population',
                                  header=0,
                                  index_col=0)

In [12]:
len(list_of_tables)

3

In [17]:
list_of_tables[1]

,Country (or dependent territory),Population,Date,% of world population,Source
Rank,,,,,
1,China[Note 2],1381560000,"February 15, 2017",18.5%,Official population clock
2,India,1312010000,"February 15, 2017",17.5%,Official population clock
3,United States[Note 3],324532000,"February 15, 2017",4.34%,Official population clock
4,Indonesia,260581000,"July 1, 2016",3.48%,UN Projection
5,Brazil,207100000,"February 15, 2017",2.77%,Official population clock
6,Pakistan,196368000,"February 15, 2017",2.62%,Official population clock
7,Nigeria,186988000,"July 1, 2016",2.5%,UN Projection
8,Bangladesh,161947000,"February 15, 2017",2.16%,Official population clock
9,Russia[Note 4],146838993,"January 1, 2017",1.96%,Official estimate
10,Japan,126860000,"January 1, 2017",1.690%,Monthly provisional estimate
11,Mexico,122273000,"July 1, 2016",1.63%,Official projection
12,Philippines,103612000,"February 15, 2017",1.38%,Official population clock
13,Ethiopia,101853000,"July 1, 2016",1.36%,UN Projection
14,Vietnam,92700000,"July 1, 2016",1.24%,Annual official projection
15,Egypt,92483100,"February 15, 2017",1.24%,Official population clock
16,Democratic Republic of the Congo,82243000,"July 1, 2017",1.10%,UN Projection
17,Germany,82175700,"December 31, 2015",1.10%,Official estimate
18,Iran,79912200,"February 15, 2017",1.07%,Official population clock
19,Turkey,79814871,"December 31, 2016",1.07%,Annual official estimate
20,Thailand,68147000,"July 1, 2016",0.91%,UN Projection
21,France[Note 5],66984000,"January 1, 2017",0.89%,Monthly official estimate
22,United Kingdom,65110000,"July 1, 2015",0.87%,Annual official estimate
23,Italy,60589940,"September 30, 2016",0.81%,Official estimate
24,South Africa,55908000,"July 1, 2016",0.75%,Annual official estimate
25,Tanzania[Note 6],55155000,"July 1, 2016",0.74%,UN projection
26,Myanmar,54363000,"July 1, 2016",0.73%,UN projection
27,South Korea,51446201,"July 1, 2017",0.69%,Annual official estimate
28,Colombia,49089500,"February 15, 2017",0.656%,Official population clock
29,Kenya,47251000,"July 1, 2016",0.63%,UN projection
30,Spain,46812000,"July 1, 2016",0.63%,Official estimate
...,...,...,...,...,...
189,Saint Kitts and Nevis,46204,"May 15, 2011",0.00062%,2011 census result
–,Sint Maarten (Netherlands),39410,"January 1, 2016",0.00053%,Official estimate
190,Monaco,38400,"December 31, 2015",0.00051%,Annual official estimate
191,Liechtenstein,37686,"June 30, 2016",0.0005%,Semi annual official estimate
–,Saint-Martin (France),36457,"January 1, 2015",0.00049%,Annual official estimate
–,Gibraltar (UK),33140,"December 31, 2014",0.00044%,Annual official estimate
192,San Marino,33121,"September 30, 2016",0.00044%,Monthly official estimate
–,Turks and Caicos Islands (UK),31458,"January 25, 2012",0.00042%,2012 census result
–,British Virgin Islands (UK),28514,"July 1, 2013",0.00038%,Official estimate
–,Bonaire (Netherlands),18905,"January 1, 2015",0.00025%,Official estimate
–,Cook Islands (NZ),18100,"March 1, 2016",0.00024%,Official quarterly estimate
193,Palau,17950,"July 1, 2015",0.00024%,Annual official estimate
–,Anguilla (UK),13452,"May 11, 2011",0.00018%,Preliminary 2011 census result
–,Wallis and Futuna (France),11750,"July 1, 2015",0.00016%,Annual official estimate
194,Tuvalu,10640,"November 4, 2012",0.00014%,2012 census result
195,Nauru,10084,"October 30, 2011",0.00013%,2011 census result
–,Saint Barthélemy (France),9417,"January 1, 2015",0.00013%,Annual official estimate
–,Saint Pierre and Miquelon (France),6286,"January 1, 2015",0.000084%,Annual official estimate
–,"Saint Helena, Ascension and Tristan da Cunha (UK)",5633,"February 7, 2016",0.000075%,2016 census result
–,Montserrat (UK),4922,"May 12, 2011",0.000066%,2011 census result
–,Sint Eustatius (Netherlands),3877,"January 1, 2015",0.000052%,Official estimate
–,Falkland Islands (UK),2563,"April 15, 2012",0.000034%,2012 census result
–,Norfolk Island (Australia),2302,"August 9, 2011",0.000031%,2011 census result
–,Christmas Island (Australia),2072,"August 9, 2011",0.000028%,2011 census result
–,Saba (Netherlands),1811,"January 1, 2015",0.000024%,Official estimate
–,Niue (NZ),1470,"July 1, 2015",0.00002%,Annual official estimate
–,Tokelau (NZ),1411,"October 18, 2011",0.000019%,2011 census result
196,Vatican City,842,"January 1, 2014",0.000011%,Official estimate
–,Cocos (Keeling) Islands (Australia),550,"August 9, 2011",0.0000073%,2011 census result
–,Pitcairn Islands (UK),57,"July 1, 2014",0.00000075%,Official estimate